name: tests-expiration

on:
  pull_request:
    paths:
      - "expiration/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and run test
        run: |
          cd expiration
          npm install
          npm run test:ci
